@startuml
actor User as user
participant "Discord Bot" as bot
participant "GPTs/Llama" as ai
box Experts
participant "experts.ai" as experts
participant "recombee" as recomb
database "unico_store" as db
end box
actor HR as hr

== Job Search ==
user -> bot: Request job openings
bot -> user: Ask for CV / search criterias
user -> bot: Send CV / search criterias
bot -> ai: Send text / CV text with search prompt
ai -> bot: Return keywords from CV / normalized text
bot -> experts: Send keywords
experts -> bot: Return opportunities
bot -> user: Show opportunities
user -> hr: Start messaging

== CV Help ==
user -> bot: Request CV help
bot -> user: Ask for old CV / skills
user -> bot: Send requested
bot -> ai: Send user info with improvement prompt
ai -> bot: Send improved CV back
bot -> user: Send improved CV


@enduml